## Softmax Quiz

In [2]:
import numpy as np

# Write a function that takes as input a list of numbers, and returns
# the list of values given by the softmax function.
def softmax_1(L):
    denom = 0
    for z in L:
        denom += 2.71828**z
    softmax = []
    for z in L:
        softmax.append((2.71828**z)/denom)
    return softmax

print(softmax_1([5,6,7]))
#%timeit softmax_1([5,6,7])  # 1.22 µs ± 5.98 ns per loop


def softmax_2(L):
    denom = sum(np.exp(L))
    softmax = []
    for z in L:
        softmax.append(np.exp(z)/denom)
    return softmax

print(softmax_2([5,6,7]))
#%timeit softmax_2([5,6,7])  # 6.42 µs ± 31.6 ns per loop


def softmax_sol(L):
    expL = np.exp(L)
    sumExpL = sum(expL)
    result = []
    for i in expL:
        result.append(i*1.0/sumExpL)
    return result

print(softmax_sol([5,6,7]))
#%timeit softmax_sol([5,6,7])  # 5.81 µs ± 646 ns per loop


def softmax_short(L):
    expL = np.exp(L)
    return np.divide(expL, expL.sum())

print(softmax_short([5,6,7]))
%timeit softmax_short([5,6,7])  # 5.36 µs ± 34.2 ns per loop

[0.09003066856407584, 0.24472856574435609, 0.6652407656915682]
[0.09003057317038046, 0.24472847105479764, 0.6652409557748219]
[0.09003057317038046, 0.24472847105479764, 0.6652409557748219]
[0.09003057 0.24472847 0.66524096]
5.58 µs ± 91.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
P = np.array([.4, .2, .8, .7])
Y = np.array([1, 0, 1, 1])
np.log(P)
np.multiply(P, Y)
# z = 1 - Y
1-P

array([0.6, 0.8, 0.2, 0.3])

## Cross-Entropy Quiz

In [26]:
import numpy as np

# Write a function that takes as input two lists Y, P,
# and returns the float corresponding to their cross-entropy.
def cross_entropy(Y, P):
    P = np.array(P)
    Y = np.array(Y)
    logP = np.log(P)
    logPminus1 = np.log(1-P)

    return -sum(np.multiply(Y, logP)) - sum(np.multiply(1-Y, logPminus1))

#%timeit
cross_entropy([1, 0, 1, 1], [0.4,0.6,0.1,0.5])  # 9.38 µs ± 116 ns per loop


def cross_entropy_solution(Y, P):
    Y = np.float_(Y)
    P = np.float_(P)
    return -np.sum(Y * np.log(P) + (1 - Y) * np.log(1 - P))b

#%timeit 
cross_entropy_solution([1, 0, 1, 1], [0.4,0.6,0.1,0.5])  # 11.1 µs ± 143 ns per loop

[-0.91629073 -0.91629073 -2.30258509 -0.69314718]


4.828313737302301

## Perceptron Quiz

In [ ]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    for i in range(len(X)):
        if prediction(X[i], W, b) != y[i]:
            if y[i] == 1.0:
                W[0] += X[i][0] * learn_rate
                W[1] += X[i][1] * learn_rate
                b += learn_rate
            else:
                W[0] -= X[i][0] * learn_rate
                W[1] -= X[i][1] * learn_rate
                b -= learn_rate
    return W, b

# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines