In [9]:
import tensorflow as tf

In [10]:
# Create TensorFlow object called tensor
hello_constant = tf.constant('Hello World!')

with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


In [11]:
tf.constant([[1,2,3], [4,5,6], [7,8,9]])

<tf.Tensor 'Const_8:0' shape=(3, 3) dtype=int32>

In [20]:
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    output = sess.run(y, feed_dict={x: 'Hello World', y: 99, z: 12.34})
    print(output)

99


In [26]:
# z = x/y - 1
x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x, y), tf.cast(tf.constant(1), tf.float64))
with tf.Session() as sess:
    output = sess.run(z)
    print(output)

4.0


In [28]:
x = tf.Variable(5)  # initial value needs to be chosen
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(x))

5


In [ ]:
# example of tf.truncated_normal() and tf.zeros
n_features = 120
n_labels = 5
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))
bias = tf.Variable(tf.zeros(n_labels))

In [30]:
# Calculate the softmax of the logits
logit_data = [2.0, 1.0, 0.1]
logits = tf.placeholder(tf.float32)
softmax = tf.nn.softmax(logits)

with tf.Session() as sess:
    output = sess.run(softmax, feed_dict={logits: logit_data})
    print(output)

[ 0.65900117  0.24243298  0.09856589]


In [ ]:
# Calculate cross entropy from session
softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]
softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

cross_en = -tf.reduce_sum(tf.multiply(one_hot, tf.log(softmax)))
with tf.Session() as sess:
    output = sess.run(cross_en, feed_dict={one_hot: one_hot_data, softmax: softmax_data})
    print(output)

### Implement Batches Function

In [ ]:
import math
def batches(batch_size, features, labels):
    """
    Create batches of features and labels
    :param batch_size: The batch size
    :param features: List of features
    :param labels: List of labels
    :return: Batches of (Features, Labels)
    """
    assert len(features) == len(labels)
    
    num_batches = int(len(features) / batch_size) + 1
    
    batches = []
    for i in range(num_batches - 1):
        batch  = []
        feat = []
        lab = []
        for j in range(batch_size):
            feat.append(features[i+j])
            lab.append(labels[i+j])
        batch.append(feat)
        batch.append(lab)
        batches.append(batch)

    # last batch
    batch  = []
    feat = []
    lab = []
    for j in range(int(len(features) % batch_size)):
        feat.append(features[(batch_size * (num_batches-1)) + j])
        lab.append(labels[(batch_size * (num_batches-1)) + j])
    batch.append(feat)
    batch.append(lab)
    batches.append(batch)
    return batches

#     # simpler
#     outout_batches = []
#     sample_size = len(features)
#     for start_i in range(0, sample_size, batch_size):
#         end_i = start_i + batch_size
#         batch = [features[start_i:end_i], labels[start_i:end_i]]
#         outout_batches.append(batch)
#     return outout_batches

In [31]:
x = [[[['F11', 'F12', 'F13', 'F14'], ['F21', 'F22', 'F23', 'F24'], ['F31', 'F32', 'F33', 'F34']], [['L11', 'L12'], ['L21', 'L22'], ['L31', 'L32']]], [[['F41', 'F42', 'F43', 'F44']], [['L41', 'L42']]]]

In [44]:
for batch in x:
    print(batch[1])

[['L11', 'L12'], ['L21', 'L22'], ['L31', 'L32']]
[['L41', 'L42']]


In [57]:
from array import array
array([55], [66])

TypeError: array() argument 1 must be a unicode character, not list

### ReLU Example

In [1]:
import tensorflow as tf

output = None
hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[1.0, 2.0, 3.0, 4.0], [-1.0, -2.0, -3.0, -4.0], [11.0, 12.0, 13.0, 14.0]])

# TODO: Create Model
hidden_layer = tf.add(tf.matmul(features, weights[0]), biases[0])
hidden_layer = tf.nn.relu(hidden_layer)

output_layer = tf.add(tf.matmul(hidden_layer, weights[1]), biases[1])

# TODO: Print session results
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    output = sess.run(output_layer)
    print(output)

[[ 5.11      8.440001]
 [ 0.        0.      ]
 [24.010002 38.239998]]


### Saving Variables

In [9]:
import tensorflow as tf

tf.reset_default_graph()

save_file = './model.ckpt'

# Two Tensor Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]), name='weights_0')
bias = tf.Variable(tf.truncated_normal([3]), name='bias_0')

saver = tf.train.Saver()

# Print the name of Weights and Bias
print('Save Weights: {}'.format(weights.name))
print('Save Bias: {}'.format(bias.name))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver.save(sess, save_file)

# Remove the previous weights and bias
tf.reset_default_graph()

# Two Variables: weights and bias
bias = tf.Variable(tf.truncated_normal([3]), name='bias_0')
weights = tf.Variable(tf.truncated_normal([2, 3]) ,name='weights_0')

saver = tf.train.Saver()

# Print the name of Weights and Bias
print('Load Weights: {}'.format(weights.name))
print('Load Bias: {}'.format(bias.name))

with tf.Session() as sess:
    # Load the weights and bias - No Error
    saver.restore(sess, save_file)

print('Loaded Weights and Bias successfully.')

Save Weights: weights_0:0
Save Bias: bias_0:0
Load Weights: weights_0:0
Load Bias: bias_0:0
INFO:tensorflow:Restoring parameters from ./model.ckpt
Loaded Weights and Bias successfully.


### Dropout Example

In [11]:
import tensorflow as tf

hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[0.0, 2.0, 3.0, 4.0], [0.1, 0.2, 0.3, 0.4], [11.0, 12.0, 13.0, 14.0]])

# TODO: Create Model with Dropout
keep_prob = tf.placeholder(tf.float32)

hidden_layer = tf.add(tf.matmul(features, weights[0]), biases[0])
hidden_layer = tf.nn.relu(hidden_layer)
hidden_layer = tf.nn.dropout(hidden_layer, keep_prob)

output_layer = tf.add(tf.matmul(hidden_layer, weights[1]), biases[1])

# TODO: Print logits from a session
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    logits = sess.run(output_layer, feed_dict={keep_prob: 0.5})
    print(logits)

[[ 1.88        0.94      ]
 [ 0.30800003  0.7700001 ]
 [ 4.72       28.32      ]]
